version: 2
jobs:
  build:
    working_directory: /go/src/github.com/xtracdev/pgeventstore
    docker:
      - image: golang:1.8.1-onbuild
      - image: postgres:9.6.2
        environment:
          POSTGRES_PASSWORD: password
      - image: xtracdev/pgflywayseed
        environment:
          DB_HOST: localhost
          DB_PORT: 5432
          USER: postgres
          PASSWORK: password
          URL: jdbc:postgresql://localhost:5432/postgres

    steps:
      - checkout
      - run: go get -v -t
      - run: go get github.com/golang/protobuf/proto
      - run: go test
      - run:
          name: integration-test-deps
          command: |
            go get github.com/gucumber/gucumber/cmd/gucumber
            go get github.com/stretchr/testify/assert
            go get github.com/xtracdev/pgconn
      - run:
          name: install-schema
          command: |
            sleep 10
      - run:
          name: integration-tests
          environment:
            DB_USER: postgres
            DB_PASSWORD: password
            DB_HOST: localhost
            DB_PORT: 5432
            DB_NAME: postgres
          command: gucumber

# Next - try second job to seed db